from typing import Set

FINDINGS: str = "FINDINGS"
SPECIAL_PURPOSE: str = "SPECIAL PURPOSE"
INTERVENTIONS: str = "INTERVENTIONS"
EVENTS: str = "EVENTS"
FINDINGS_ABOUT: str = "FINDINGS ABOUT"
DETECTABLE_CLASSES: Set[str] = {FINDINGS, INTERVENTIONS, EVENTS, FINDINGS_ABOUT}
GENERAL_OBSERVATIONS_CLASS: str = "GENERAL OBSERVATIONS"
FINDINGS_TEST_VARIABLE: str = "--TEST"
