CREATE TABLE IF NOT EXISTS ig_variables (
    standard_type VARCHAR(10),
    version VARCHAR(20),
    variable_order INTEGER,
    class VARCHAR(50),
    dataset_name VARCHAR(50),
    variable_name VARCHAR(50),
    variable_label VARCHAR(255),
    structure_name VARCHAR(50),
    variable_set VARCHAR(50),
    type VARCHAR(50),
    codelist_code VARCHAR(255),
    submission_value TEXT,
    value_domain TEXT,
    value_list TEXT,
    role VARCHAR(50),
    notes TEXT,
    core VARCHAR(20),
    PRIMARY KEY (standard_type, version, dataset_name, variable_name)
)