from cdisc_rules_engine.models.sql_operation_result import SqlOperationResult
from cdisc_rules_engine.sql_operations.sql_base_operation import SqlBaseOperation

ISO_3166_COUNTRY_CODES = [
    {"country_name": "Afghanistan", "alpha_2": "AF", "alpha_3": "AFG"},
    {"country_name": "Åland Islands", "alpha_2": "AX", "alpha_3": "ALA"},
    {"country_name": "Albania", "alpha_2": "AL", "alpha_3": "ALB"},
    {"country_name": "Algeria", "alpha_2": "DZ", "alpha_3": "DZA"},
    {"country_name": "American Samoa", "alpha_2": "AS", "alpha_3": "ASM"},
    {"country_name": "Andorra", "alpha_2": "AD", "alpha_3": "AND"},
    {"country_name": "Angola", "alpha_2": "AO", "alpha_3": "AGO"},
    {"country_name": "Anguilla", "alpha_2": "AI", "alpha_3": "AIA"},
    {"country_name": "Antarctica", "alpha_2": "AQ", "alpha_3": "ATA"},
    {"country_name": "Antigua and Barbuda", "alpha_2": "AG", "alpha_3": "ATG"},
    {"country_name": "Argentina", "alpha_2": "AR", "alpha_3": "ARG"},
    {"country_name": "Armenia", "alpha_2": "AM", "alpha_3": "ARM"},
    {"country_name": "Aruba", "alpha_2": "AW", "alpha_3": "ABW"},
    {"country_name": "Australia", "alpha_2": "AU", "alpha_3": "AUS"},
    {"country_name": "Austria", "alpha_2": "AT", "alpha_3": "AUT"},
    {"country_name": "Azerbaijan", "alpha_2": "AZ", "alpha_3": "AZE"},
    {"country_name": "Bahamas", "alpha_2": "BS", "alpha_3": "BHS"},
    {"country_name": "Bahrain", "alpha_2": "BH", "alpha_3": "BHR"},
    {"country_name": "Bangladesh", "alpha_2": "BD", "alpha_3": "BGD"},
    {"country_name": "Barbados", "alpha_2": "BB", "alpha_3": "BRB"},
    {"country_name": "Belarus", "alpha_2": "BY", "alpha_3": "BLR"},
    {"country_name": "Belgium", "alpha_2": "BE", "alpha_3": "BEL"},
    {"country_name": "Belize", "alpha_2": "BZ", "alpha_3": "BLZ"},
    {"country_name": "Benin", "alpha_2": "BJ", "alpha_3": "BEN"},
    {"country_name": "Bermuda", "alpha_2": "BM", "alpha_3": "BMU"},
    {"country_name": "Bhutan", "alpha_2": "BT", "alpha_3": "BTN"},
    {"country_name": "Bolivia (Plurinational State of)", "alpha_2": "BO", "alpha_3": "BOL"},
    {"country_name": "Bonaire, Sint Eustatius and Saba", "alpha_2": "BQ", "alpha_3": "BES"},
    {"country_name": "Bosnia and Herzegovina", "alpha_2": "BA", "alpha_3": "BIH"},
    {"country_name": "Botswana", "alpha_2": "BW", "alpha_3": "BWA"},
    {"country_name": "Bouvet Island", "alpha_2": "BV", "alpha_3": "BVT"},
    {"country_name": "Brazil", "alpha_2": "BR", "alpha_3": "BRA"},
    {"country_name": "British Indian Ocean Territory", "alpha_2": "IO", "alpha_3": "IOT"},
    {"country_name": "Brunei Darussalam", "alpha_2": "BN", "alpha_3": "BRN"},
    {"country_name": "Bulgaria", "alpha_2": "BG", "alpha_3": "BGR"},
    {"country_name": "Burkina Faso", "alpha_2": "BF", "alpha_3": "BFA"},
    {"country_name": "Burundi", "alpha_2": "BI", "alpha_3": "BDI"},
    {"country_name": "Cabo Verde", "alpha_2": "CV", "alpha_3": "CPV"},
    {"country_name": "Cambodia", "alpha_2": "KH", "alpha_3": "KHM"},
    {"country_name": "Cameroon", "alpha_2": "CM", "alpha_3": "CMR"},
    {"country_name": "Canada", "alpha_2": "CA", "alpha_3": "CAN"},
    {"country_name": "Cayman Islands", "alpha_2": "KY", "alpha_3": "CYM"},
    {"country_name": "Central African Republic", "alpha_2": "CF", "alpha_3": "CAF"},
    {"country_name": "Chad", "alpha_2": "TD", "alpha_3": "TCD"},
    {"country_name": "Chile", "alpha_2": "CL", "alpha_3": "CHL"},
    {"country_name": "China", "alpha_2": "CN", "alpha_3": "CHN"},
    {"country_name": "Christmas Island", "alpha_2": "CX", "alpha_3": "CXR"},
    {"country_name": "Cocos (Keeling) Islands", "alpha_2": "CC", "alpha_3": "CCK"},
    {"country_name": "Colombia", "alpha_2": "CO", "alpha_3": "COL"},
    {"country_name": "Comoros", "alpha_2": "KM", "alpha_3": "COM"},
    {"country_name": "Congo (Democratic Republic of the)", "alpha_2": "CD", "alpha_3": "COD"},
    {"country_name": "Congo", "alpha_2": "CG", "alpha_3": "COG"},
    {"country_name": "Cook Islands", "alpha_2": "CK", "alpha_3": "COK"},
    {"country_name": "Costa Rica", "alpha_2": "CR", "alpha_3": "CRI"},
    {"country_name": "Côte d'Ivoire", "alpha_2": "CI", "alpha_3": "CIV"},
    {"country_name": "Croatia", "alpha_2": "HR", "alpha_3": "HRV"},
    {"country_name": "Cuba", "alpha_2": "CU", "alpha_3": "CUB"},
    {"country_name": "Curaçao", "alpha_2": "CW", "alpha_3": "CUW"},
    {"country_name": "Cyprus", "alpha_2": "CY", "alpha_3": "CYP"},
    {"country_name": "Czechia", "alpha_2": "CZ", "alpha_3": "CZE"},
    {"country_name": "Denmark", "alpha_2": "DK", "alpha_3": "DNK"},
    {"country_name": "Djibouti", "alpha_2": "DJ", "alpha_3": "DJI"},
    {"country_name": "Dominica", "alpha_2": "DM", "alpha_3": "DMA"},
    {"country_name": "Dominican Republic", "alpha_2": "DO", "alpha_3": "DOM"},
    {"country_name": "Ecuador", "alpha_2": "EC", "alpha_3": "ECU"},
    {"country_name": "Egypt", "alpha_2": "EG", "alpha_3": "EGY"},
    {"country_name": "El Salvador", "alpha_2": "SV", "alpha_3": "SLV"},
    {"country_name": "Equatorial Guinea", "alpha_2": "GQ", "alpha_3": "GNQ"},
    {"country_name": "Eritrea", "alpha_2": "ER", "alpha_3": "ERI"},
    {"country_name": "Estonia", "alpha_2": "EE", "alpha_3": "EST"},
    {"country_name": "Eswatini", "alpha_2": "SZ", "alpha_3": "SWZ"},
    {"country_name": "Ethiopia", "alpha_2": "ET", "alpha_3": "ETH"},
    {"country_name": "Falkland Islands (Malvinas)", "alpha_2": "FK", "alpha_3": "FLK"},
    {"country_name": "Faroe Islands", "alpha_2": "FO", "alpha_3": "FRO"},
    {"country_name": "Fiji", "alpha_2": "FJ", "alpha_3": "FJI"},
    {"country_name": "Finland", "alpha_2": "FI", "alpha_3": "FIN"},
    {"country_name": "France", "alpha_2": "FR", "alpha_3": "FRA"},
    {"country_name": "French Guiana", "alpha_2": "GF", "alpha_3": "GUF"},
    {"country_name": "French Polynesia", "alpha_2": "PF", "alpha_3": "PYF"},
    {"country_name": "French Southern Territories", "alpha_2": "TF", "alpha_3": "ATF"},
    {"country_name": "Gabon", "alpha_2": "GA", "alpha_3": "GAB"},
    {"country_name": "Gambia", "alpha_2": "GM", "alpha_3": "GMB"},
    {"country_name": "Georgia", "alpha_2": "GE", "alpha_3": "GEO"},
    {"country_name": "Germany", "alpha_2": "DE", "alpha_3": "DEU"},
    {"country_name": "Ghana", "alpha_2": "GH", "alpha_3": "GHA"},
    {"country_name": "Gibraltar", "alpha_2": "GI", "alpha_3": "GIB"},
    {"country_name": "Greece", "alpha_2": "GR", "alpha_3": "GRC"},
    {"country_name": "Greenland", "alpha_2": "GL", "alpha_3": "GRL"},
    {"country_name": "Grenada", "alpha_2": "GD", "alpha_3": "GRD"},
    {"country_name": "Guadeloupe", "alpha_2": "GP", "alpha_3": "GLP"},
    {"country_name": "Guam", "alpha_2": "GU", "alpha_3": "GUM"},
    {"country_name": "Guatemala", "alpha_2": "GT", "alpha_3": "GTM"},
    {"country_name": "Guernsey", "alpha_2": "GG", "alpha_3": "GGY"},
    {"country_name": "Guinea", "alpha_2": "GN", "alpha_3": "GIN"},
    {"country_name": "Guinea-Bissau", "alpha_2": "GW", "alpha_3": "GNB"},
    {"country_name": "Guyana", "alpha_2": "GY", "alpha_3": "GUY"},
    {"country_name": "Haiti", "alpha_2": "HT", "alpha_3": "HTI"},
    {"country_name": "Heard Island and McDonald Islands", "alpha_2": "HM", "alpha_3": "HMD"},
    {"country_name": "Holy See", "alpha_2": "VA", "alpha_3": "VAT"},
    {"country_name": "Honduras", "alpha_2": "HN", "alpha_3": "HND"},
    {"country_name": "Hong Kong", "alpha_2": "HK", "alpha_3": "HKG"},
    {"country_name": "Hungary", "alpha_2": "HU", "alpha_3": "HUN"},
    {"country_name": "Iceland", "alpha_2": "IS", "alpha_3": "ISL"},
    {"country_name": "India", "alpha_2": "IN", "alpha_3": "IND"},
    {"country_name": "Indonesia", "alpha_2": "ID", "alpha_3": "IDN"},
    {"country_name": "Iran (Islamic Republic of)", "alpha_2": "IR", "alpha_3": "IRN"},
    {"country_name": "Iraq", "alpha_2": "IQ", "alpha_3": "IRQ"},
    {"country_name": "Ireland", "alpha_2": "IE", "alpha_3": "IRL"},
    {"country_name": "Isle of Man", "alpha_2": "IM", "alpha_3": "IMN"},
    {"country_name": "Israel", "alpha_2": "IL", "alpha_3": "ISR"},
    {"country_name": "Italy", "alpha_2": "IT", "alpha_3": "ITA"},
    {"country_name": "Jamaica", "alpha_2": "JM", "alpha_3": "JAM"},
    {"country_name": "Japan", "alpha_2": "JP", "alpha_3": "JPN"},
    {"country_name": "Jersey", "alpha_2": "JE", "alpha_3": "JEY"},
    {"country_name": "Jordan", "alpha_2": "JO", "alpha_3": "JOR"},
    {"country_name": "Kazakhstan", "alpha_2": "KZ", "alpha_3": "KAZ"},
    {"country_name": "Kenya", "alpha_2": "KE", "alpha_3": "KEN"},
    {"country_name": "Kiribati", "alpha_2": "KI", "alpha_3": "KIR"},
    {"country_name": "Korea (Democratic People's Republic of)", "alpha_2": "KP", "alpha_3": "PRK"},
    {"country_name": "Korea (Republic of)", "alpha_2": "KR", "alpha_3": "KOR"},
    {"country_name": "Kuwait", "alpha_2": "KW", "alpha_3": "KWT"},
    {"country_name": "Kyrgyzstan", "alpha_2": "KG", "alpha_3": "KGZ"},
    {"country_name": "Lao People's Democratic Republic", "alpha_2": "LA", "alpha_3": "LAO"},
    {"country_name": "Latvia", "alpha_2": "LV", "alpha_3": "LVA"},
    {"country_name": "Lebanon", "alpha_2": "LB", "alpha_3": "LBN"},
    {"country_name": "Lesotho", "alpha_2": "LS", "alpha_3": "LSO"},
    {"country_name": "Liberia", "alpha_2": "LR", "alpha_3": "LBR"},
    {"country_name": "Libya", "alpha_2": "LY", "alpha_3": "LBY"},
    {"country_name": "Liechtenstein", "alpha_2": "LI", "alpha_3": "LIE"},
    {"country_name": "Lithuania", "alpha_2": "LT", "alpha_3": "LTU"},
    {"country_name": "Luxembourg", "alpha_2": "LU", "alpha_3": "LUX"},
    {"country_name": "Macao", "alpha_2": "MO", "alpha_3": "MAC"},
    {"country_name": "Madagascar", "alpha_2": "MG", "alpha_3": "MDG"},
    {"country_name": "Malawi", "alpha_2": "MW", "alpha_3": "MWI"},
    {"country_name": "Malaysia", "alpha_2": "MY", "alpha_3": "MYS"},
    {"country_name": "Maldives", "alpha_2": "MV", "alpha_3": "MDV"},
    {"country_name": "Mali", "alpha_2": "ML", "alpha_3": "MLI"},
    {"country_name": "Malta", "alpha_2": "MT", "alpha_3": "MLT"},
    {"country_name": "Marshall Islands", "alpha_2": "MH", "alpha_3": "MHL"},
    {"country_name": "Martinique", "alpha_2": "MQ", "alpha_3": "MTQ"},
    {"country_name": "Mauritania", "alpha_2": "MR", "alpha_3": "MRT"},
    {"country_name": "Mauritius", "alpha_2": "MU", "alpha_3": "MUS"},
    {"country_name": "Mayotte", "alpha_2": "YT", "alpha_3": "MYT"},
    {"country_name": "Mexico", "alpha_2": "MX", "alpha_3": "MEX"},
    {"country_name": "Micronesia (Federated States of)", "alpha_2": "FM", "alpha_3": "FSM"},
    {"country_name": "Moldova (Republic of)", "alpha_2": "MD", "alpha_3": "MDA"},
    {"country_name": "Monaco", "alpha_2": "MC", "alpha_3": "MCO"},
    {"country_name": "Mongolia", "alpha_2": "MN", "alpha_3": "MNG"},
    {"country_name": "Montenegro", "alpha_2": "ME", "alpha_3": "MNE"},
    {"country_name": "Montserrat", "alpha_2": "MS", "alpha_3": "MSR"},
    {"country_name": "Morocco", "alpha_2": "MA", "alpha_3": "MAR"},
    {"country_name": "Mozambique", "alpha_2": "MZ", "alpha_3": "MOZ"},
    {"country_name": "Myanmar", "alpha_2": "MM", "alpha_3": "MMR"},
    {"country_name": "Namibia", "alpha_2": "NA", "alpha_3": "NAM"},
    {"country_name": "Nauru", "alpha_2": "NR", "alpha_3": "NRU"},
    {"country_name": "Nepal", "alpha_2": "NP", "alpha_3": "NPL"},
    {"country_name": "Netherlands", "alpha_2": "NL", "alpha_3": "NLD"},
    {"country_name": "New Caledonia", "alpha_2": "NC", "alpha_3": "NCL"},
    {"country_name": "New Zealand", "alpha_2": "NZ", "alpha_3": "NZL"},
    {"country_name": "Nicaragua", "alpha_2": "NI", "alpha_3": "NIC"},
    {"country_name": "Niger", "alpha_2": "NE", "alpha_3": "NER"},
    {"country_name": "Nigeria", "alpha_2": "NG", "alpha_3": "NGA"},
    {"country_name": "Niue", "alpha_2": "NU", "alpha_3": "NIU"},
    {"country_name": "Norfolk Island", "alpha_2": "NF", "alpha_3": "NFK"},
    {"country_name": "North Macedonia", "alpha_2": "MK", "alpha_3": "MKD"},
    {"country_name": "Northern Mariana Islands", "alpha_2": "MP", "alpha_3": "MNP"},
    {"country_name": "Norway", "alpha_2": "NO", "alpha_3": "NOR"},
    {"country_name": "Oman", "alpha_2": "OM", "alpha_3": "OMN"},
    {"country_name": "Pakistan", "alpha_2": "PK", "alpha_3": "PAK"},
    {"country_name": "Palau", "alpha_2": "PW", "alpha_3": "PLW"},
    {"country_name": "Palestine, State of", "alpha_2": "PS", "alpha_3": "PSE"},
    {"country_name": "Panama", "alpha_2": "PA", "alpha_3": "PAN"},
    {"country_name": "Papua New Guinea", "alpha_2": "PG", "alpha_3": "PNG"},
    {"country_name": "Paraguay", "alpha_2": "PY", "alpha_3": "PRY"},
    {"country_name": "Peru", "alpha_2": "PE", "alpha_3": "PER"},
    {"country_name": "Philippines", "alpha_2": "PH", "alpha_3": "PHL"},
    {"country_name": "Pitcairn", "alpha_2": "PN", "alpha_3": "PCN"},
    {"country_name": "Poland", "alpha_2": "PL", "alpha_3": "POL"},
    {"country_name": "Portugal", "alpha_2": "PT", "alpha_3": "PRT"},
    {"country_name": "Puerto Rico", "alpha_2": "PR", "alpha_3": "PRI"},
    {"country_name": "Qatar", "alpha_2": "QA", "alpha_3": "QAT"},
    {"country_name": "Réunion", "alpha_2": "RE", "alpha_3": "REU"},
    {"country_name": "Romania", "alpha_2": "RO", "alpha_3": "ROU"},
    {"country_name": "Russian Federation", "alpha_2": "RU", "alpha_3": "RUS"},
    {"country_name": "Rwanda", "alpha_2": "RW", "alpha_3": "RWA"},
    {"country_name": "Saint Barthélemy", "alpha_2": "BL", "alpha_3": "BLM"},
    {"country_name": "Saint Helena, Ascension and Tristan da Cunha", "alpha_2": "SH", "alpha_3": "SHN"},
    {"country_name": "Saint Kitts and Nevis", "alpha_2": "KN", "alpha_3": "KNA"},
    {"country_name": "Saint Lucia", "alpha_2": "LC", "alpha_3": "LCA"},
    {"country_name": "Saint Martin (French part)", "alpha_2": "MF", "alpha_3": "MAF"},
    {"country_name": "Saint Pierre and Miquelon", "alpha_2": "PM", "alpha_3": "SPM"},
    {"country_name": "Saint Vincent and the Grenadines", "alpha_2": "VC", "alpha_3": "VCT"},
    {"country_name": "Samoa", "alpha_2": "WS", "alpha_3": "WSM"},
    {"country_name": "San Marino", "alpha_2": "SM", "alpha_3": "SMR"},
    {"country_name": "Sao Tome and Principe", "alpha_2": "ST", "alpha_3": "STP"},
    {"country_name": "Saudi Arabia", "alpha_2": "SA", "alpha_3": "SAU"},
    {"country_name": "Senegal", "alpha_2": "SN", "alpha_3": "SEN"},
    {"country_name": "Serbia", "alpha_2": "RS", "alpha_3": "SRB"},
    {"country_name": "Seychelles", "alpha_2": "SC", "alpha_3": "SYC"},
    {"country_name": "Sierra Leone", "alpha_2": "SL", "alpha_3": "SLE"},
    {"country_name": "Singapore", "alpha_2": "SG", "alpha_3": "SGP"},
    {"country_name": "Sint Maarten (Dutch part)", "alpha_2": "SX", "alpha_3": "SXM"},
    {"country_name": "Slovakia", "alpha_2": "SK", "alpha_3": "SVK"},
    {"country_name": "Slovenia", "alpha_2": "SI", "alpha_3": "SVN"},
    {"country_name": "Solomon Islands", "alpha_2": "SB", "alpha_3": "SLB"},
    {"country_name": "Somalia", "alpha_2": "SO", "alpha_3": "SOM"},
    {"country_name": "South Africa", "alpha_2": "ZA", "alpha_3": "ZAF"},
    {"country_name": "South Georgia and the South Sandwich Islands", "alpha_2": "GS", "alpha_3": "SGS"},
    {"country_name": "South Sudan", "alpha_2": "SS", "alpha_3": "SSD"},
    {"country_name": "Spain", "alpha_2": "ES", "alpha_3": "ESP"},
    {"country_name": "Sri Lanka", "alpha_2": "LK", "alpha_3": "LKA"},
    {"country_name": "Sudan", "alpha_2": "SD", "alpha_3": "SDN"},
    {"country_name": "Suriname", "alpha_2": "SR", "alpha_3": "SUR"},
    {"country_name": "Svalbard and Jan Mayen", "alpha_2": "SJ", "alpha_3": "SJM"},
    {"country_name": "Sweden", "alpha_2": "SE", "alpha_3": "SWE"},
    {"country_name": "Switzerland", "alpha_2": "CH", "alpha_3": "CHE"},
    {"country_name": "Syrian Arab Republic", "alpha_2": "SY", "alpha_3": "SYR"},
    {"country_name": "Taiwan (Province of China)", "alpha_2": "TW", "alpha_3": "TWN"},
    {"country_name": "Tajikistan", "alpha_2": "TJ", "alpha_3": "TJK"},
    {"country_name": "Tanzania, United Republic of", "alpha_2": "TZ", "alpha_3": "TZA"},
    {"country_name": "Thailand", "alpha_2": "TH", "alpha_3": "THA"},
    {"country_name": "Timor-Leste", "alpha_2": "TL", "alpha_3": "TLS"},
    {"country_name": "Togo", "alpha_2": "TG", "alpha_3": "TGO"},
    {"country_name": "Tokelau", "alpha_2": "TK", "alpha_3": "TKL"},
    {"country_name": "Tonga", "alpha_2": "TO", "alpha_3": "TON"},
    {"country_name": "Trinidad and Tobago", "alpha_2": "TT", "alpha_3": "TTO"},
    {"country_name": "Tunisia", "alpha_2": "TN", "alpha_3": "TUN"},
    {"country_name": "Türkiye", "alpha_2": "TR", "alpha_3": "TUR"},
    {"country_name": "Turkmenistan", "alpha_2": "TM", "alpha_3": "TKM"},
    {"country_name": "Turks and Caicos Islands", "alpha_2": "TC", "alpha_3": "TCA"},
    {"country_name": "Tuvalu", "alpha_2": "TV", "alpha_3": "TUV"},
    {"country_name": "Uganda", "alpha_2": "UG", "alpha_3": "UGA"},
    {"country_name": "Ukraine", "alpha_2": "UA", "alpha_3": "UKR"},
    {"country_name": "United Arab Emirates", "alpha_2": "AE", "alpha_3": "ARE"},
    {"country_name": "United Kingdom", "alpha_2": "GB", "alpha_3": "GBR"},
    {"country_name": "United States Minor Outlying Islands", "alpha_2": "UM", "alpha_3": "UMI"},
    {"country_name": "United States", "alpha_2": "US", "alpha_3": "USA"},
    {"country_name": "Uruguay", "alpha_2": "UY", "alpha_3": "URY"},
    {"country_name": "Uzbekistan", "alpha_2": "UZ", "alpha_3": "UZB"},
    {"country_name": "Vanuatu", "alpha_2": "VU", "alpha_3": "VUT"},
    {"country_name": "Venezuela (Bolivarian Republic of)", "alpha_2": "VE", "alpha_3": "VEN"},
    {"country_name": "Viet Nam", "alpha_2": "VN", "alpha_3": "VNM"},
    {"country_name": "Virgin Islands (British)", "alpha_2": "VG", "alpha_3": "VGB"},
    {"country_name": "Virgin Islands (U.S.)", "alpha_2": "VI", "alpha_3": "VIR"},
    {"country_name": "Wallis and Futuna", "alpha_2": "WF", "alpha_3": "WLF"},
    {"country_name": "Western Sahara", "alpha_2": "EH", "alpha_3": "ESH"},
    {"country_name": "Yemen", "alpha_2": "YE", "alpha_3": "YEM"},
    {"country_name": "Zambia", "alpha_2": "ZM", "alpha_3": "ZMB"},
    {"country_name": "Zimbabwe", "alpha_2": "ZW", "alpha_3": "ZWE"},
]

GENC_COUNTRY_CODES = [
    {"country_name": "Afghanistan", "alpha_2": "AF", "alpha_3": "AFG"},
    {"country_name": "Akrotiri", "alpha_2": "QZ", "alpha_3": "XQZ"},
    {"country_name": "Albania", "alpha_2": "AL", "alpha_3": "ALB"},
    {"country_name": "Algeria", "alpha_2": "DZ", "alpha_3": "DZA"},
    {"country_name": "American Samoa", "alpha_2": "AS", "alpha_3": "ASM"},
    {"country_name": "Andorra", "alpha_2": "AD", "alpha_3": "AND"},
    {"country_name": "Angola", "alpha_2": "AO", "alpha_3": "AGO"},
    {"country_name": "Anguilla", "alpha_2": "AI", "alpha_3": "AIA"},
    {"country_name": "Antarctica", "alpha_2": "AQ", "alpha_3": "ATA"},
    {"country_name": "Antigua and Barbuda", "alpha_2": "AG", "alpha_3": "ATG"},
    {"country_name": "Argentina", "alpha_2": "AR", "alpha_3": "ARG"},
    {"country_name": "Armenia", "alpha_2": "AM", "alpha_3": "ARM"},
    {"country_name": "Aruba", "alpha_2": "AW", "alpha_3": "ABW"},
    {"country_name": "Ashmore and Cartier Islands", "alpha_2": "XA", "alpha_3": "XAC"},
    {"country_name": "Australia", "alpha_2": "AU", "alpha_3": "AUS"},
    {"country_name": "Austria", "alpha_2": "AT", "alpha_3": "AUT"},
    {"country_name": "Azerbaijan", "alpha_2": "AZ", "alpha_3": "AZE"},
    {"country_name": "Bahamas, The", "alpha_2": "BS", "alpha_3": "BHS"},
    {"country_name": "Bahrain", "alpha_2": "BH", "alpha_3": "BHR"},
    {"country_name": "Baker Island", "alpha_2": "XB", "alpha_3": "XBK"},
    {"country_name": "Bangladesh", "alpha_2": "BD", "alpha_3": "BGD"},
    {"country_name": "Barbados", "alpha_2": "BB", "alpha_3": "BRB"},
    {"country_name": "Bassas da India", "alpha_2": "QS", "alpha_3": "XBI"},
    {"country_name": "Belarus", "alpha_2": "BY", "alpha_3": "BLR"},
    {"country_name": "Belgium", "alpha_2": "BE", "alpha_3": "BEL"},
    {"country_name": "Belize", "alpha_2": "BZ", "alpha_3": "BLZ"},
    {"country_name": "Benin", "alpha_2": "BJ", "alpha_3": "BEN"},
    {"country_name": "Bermuda", "alpha_2": "BM", "alpha_3": "BMU"},
    {"country_name": "Bhutan", "alpha_2": "BT", "alpha_3": "BTN"},
    {"country_name": "Bolivia (Plurinational State of)", "alpha_2": "BO", "alpha_3": "BOL"},
    {"country_name": "Bonaire, Sint Eustatius and Saba", "alpha_2": "BQ", "alpha_3": "BES"},
    {"country_name": "Bosnia and Herzegovina", "alpha_2": "BA", "alpha_3": "BIH"},
    {"country_name": "Botswana", "alpha_2": "BW", "alpha_3": "BWA"},
    {"country_name": "Bouvet Island", "alpha_2": "BV", "alpha_3": "BVT"},
    {"country_name": "Brazil", "alpha_2": "BR", "alpha_3": "BRA"},
    {"country_name": "British Indian Ocean Territory", "alpha_2": "IO", "alpha_3": "IOT"},
    {"country_name": "Brunei Darussalam", "alpha_2": "BN", "alpha_3": "BRN"},
    {"country_name": "Bulgaria", "alpha_2": "BG", "alpha_3": "BGR"},
    {"country_name": "Burkina Faso", "alpha_2": "BF", "alpha_3": "BFA"},
    {"country_name": "Burma", "alpha_2": "MM", "alpha_3": "MMR"},
    {"country_name": "Burundi", "alpha_2": "BI", "alpha_3": "BDI"},
    {"country_name": "Cabo Verde", "alpha_2": "CV", "alpha_3": "CPV"},
    {"country_name": "Cambodia", "alpha_2": "KH", "alpha_3": "KHM"},
    {"country_name": "Cameroon", "alpha_2": "CM", "alpha_3": "CMR"},
    {"country_name": "Canada", "alpha_2": "CA", "alpha_3": "CAN"},
    {"country_name": "Cayman Islands", "alpha_2": "KY", "alpha_3": "CYM"},
    {"country_name": "Central African Republic", "alpha_2": "CF", "alpha_3": "CAF"},
    {"country_name": "Chad", "alpha_2": "TD", "alpha_3": "TCD"},
    {"country_name": "Chile", "alpha_2": "CL", "alpha_3": "CHL"},
    {"country_name": "China", "alpha_2": "CN", "alpha_3": "CHN"},
    {"country_name": "Christmas Island", "alpha_2": "CX", "alpha_3": "CXR"},
    {"country_name": "Clipperton Island", "alpha_2": "CP", "alpha_3": "CPT"},
    {"country_name": "Cocos (Keeling) Islands", "alpha_2": "CC", "alpha_3": "CCK"},
    {"country_name": "Colombia", "alpha_2": "CO", "alpha_3": "COL"},
    {"country_name": "Comoros", "alpha_2": "KM", "alpha_3": "COM"},
    {"country_name": "Congo", "alpha_2": "CG", "alpha_3": "COG"},
    {"country_name": "Congo (Democratic Republic of the)", "alpha_2": "CD", "alpha_3": "COD"},
    {"country_name": "Cook Islands", "alpha_2": "CK", "alpha_3": "COK"},
    {"country_name": "Coral Sea Islands", "alpha_2": "XC", "alpha_3": "XCS"},
    {"country_name": "Costa Rica", "alpha_2": "CR", "alpha_3": "CRI"},
    {"country_name": "Cote d'Ivoire", "alpha_2": "CI", "alpha_3": "CIV"},
    {"country_name": "Croatia", "alpha_2": "HR", "alpha_3": "HRV"},
    {"country_name": "Cuba", "alpha_2": "CU", "alpha_3": "CUB"},
    {"country_name": "Curacao", "alpha_2": "CW", "alpha_3": "CUW"},
    {"country_name": "Cyprus", "alpha_2": "CY", "alpha_3": "CYP"},
    {"country_name": "Czechia", "alpha_2": "CZ", "alpha_3": "CZE"},
    {"country_name": "Denmark", "alpha_2": "DK", "alpha_3": "DNK"},
    {"country_name": "Dhekelia", "alpha_2": "XD", "alpha_3": "XXD"},
    {"country_name": "Diego Garcia", "alpha_2": "DG", "alpha_3": "DGA"},
    {"country_name": "Djibouti", "alpha_2": "DJ", "alpha_3": "DJI"},
    {"country_name": "Dominica", "alpha_2": "DM", "alpha_3": "DMA"},
    {"country_name": "Dominican Republic", "alpha_2": "DO", "alpha_3": "DOM"},
    {"country_name": "Ecuador", "alpha_2": "EC", "alpha_3": "ECU"},
    {"country_name": "Egypt", "alpha_2": "EG", "alpha_3": "EGY"},
    {"country_name": "El Salvador", "alpha_2": "SV", "alpha_3": "SLV"},
    {"country_name": "Equatorial Guinea", "alpha_2": "GQ", "alpha_3": "GNQ"},
    {"country_name": "Eritrea", "alpha_2": "ER", "alpha_3": "ERI"},
    {"country_name": "Estonia", "alpha_2": "EE", "alpha_3": "EST"},
    {"country_name": "Ethiopia", "alpha_2": "ET", "alpha_3": "ETH"},
    {"country_name": "Europa Island", "alpha_2": "XE", "alpha_3": "XEU"},
    {"country_name": "Falkland Islands (Malvinas)", "alpha_2": "FK", "alpha_3": "FLK"},
    {"country_name": "Faroe Islands", "alpha_2": "FO", "alpha_3": "FRO"},
    {"country_name": "Fiji", "alpha_2": "FJ", "alpha_3": "FJI"},
    {"country_name": "Finland", "alpha_2": "FI", "alpha_3": "FIN"},
    {"country_name": "France", "alpha_2": "FR", "alpha_3": "FRA"},
    {"country_name": "French Guiana", "alpha_2": "GF", "alpha_3": "GUF"},
    {"country_name": "French Polynesia", "alpha_2": "PF", "alpha_3": "PYF"},
    {"country_name": "French Southern and Antarctic Lands", "alpha_2": "TF", "alpha_3": "ATF"},
    {"country_name": "Gabon", "alpha_2": "GA", "alpha_3": "GAB"},
    {"country_name": "Gambia, The", "alpha_2": "GM", "alpha_3": "GMB"},
    {"country_name": "Gaza Strip", "alpha_2": "XG", "alpha_3": "XGZ"},
    {"country_name": "Georgia", "alpha_2": "GE", "alpha_3": "GEO"},
    {"country_name": "Germany", "alpha_2": "DE", "alpha_3": "DEU"},
    {"country_name": "Ghana", "alpha_2": "GH", "alpha_3": "GHA"},
    {"country_name": "Gibraltar", "alpha_2": "GI", "alpha_3": "GIB"},
    {"country_name": "Glorioso Islands", "alpha_2": "QX", "alpha_3": "XGL"},
    {"country_name": "Greece", "alpha_2": "GR", "alpha_3": "GRC"},
    {"country_name": "Greenland", "alpha_2": "GL", "alpha_3": "GRL"},
    {"country_name": "Grenada", "alpha_2": "GD", "alpha_3": "GRD"},
    {"country_name": "Guadeloupe", "alpha_2": "GP", "alpha_3": "GLP"},
    {"country_name": "Guam", "alpha_2": "GU", "alpha_3": "GUM"},
    {"country_name": "Guantanamo Bay Naval Base", "alpha_2": "A2", "alpha_3": "AX2"},
    {"country_name": "Guatemala", "alpha_2": "GT", "alpha_3": "GTM"},
    {"country_name": "Guernsey", "alpha_2": "GG", "alpha_3": "GGY"},
    {"country_name": "Guinea", "alpha_2": "GN", "alpha_3": "GIN"},
    {"country_name": "Guinea-Bissau", "alpha_2": "GW", "alpha_3": "GNB"},
    {"country_name": "Guyana", "alpha_2": "GY", "alpha_3": "GUY"},
    {"country_name": "Haiti", "alpha_2": "HT", "alpha_3": "HTI"},
    {"country_name": "Heard Island and McDonald Islands", "alpha_2": "HM", "alpha_3": "HMD"},
    {"country_name": "Holy See (Vatican City State)", "alpha_2": "VA", "alpha_3": "VAT"},
    {"country_name": "Honduras", "alpha_2": "HN", "alpha_3": "HND"},
    {"country_name": "Hong Kong", "alpha_2": "HK", "alpha_3": "HKG"},
    {"country_name": "Hungary", "alpha_2": "HU", "alpha_3": "HUN"},
    {"country_name": "Iceland", "alpha_2": "IS", "alpha_3": "ISL"},
    {"country_name": "India", "alpha_2": "IN", "alpha_3": "IND"},
    {"country_name": "Indonesia", "alpha_2": "ID", "alpha_3": "IDN"},
    {"country_name": "Iran (Islamic Republic of)", "alpha_2": "IR", "alpha_3": "IRN"},
    {"country_name": "Iraq", "alpha_2": "IQ", "alpha_3": "IRQ"},
    {"country_name": "Ireland", "alpha_2": "IE", "alpha_3": "IRL"},
    {"country_name": "Isle of Man", "alpha_2": "IM", "alpha_3": "IMN"},
    {"country_name": "Israel", "alpha_2": "IL", "alpha_3": "ISR"},
    {"country_name": "Italy", "alpha_2": "IT", "alpha_3": "ITA"},
    {"country_name": "Jamaica", "alpha_2": "JM", "alpha_3": "JAM"},
    {"country_name": "Japan", "alpha_2": "JP", "alpha_3": "JPN"},
    {"country_name": "Jersey", "alpha_2": "JE", "alpha_3": "JEY"},
    {"country_name": "Jordan", "alpha_2": "JO", "alpha_3": "JOR"},
    {"country_name": "Kazakhstan", "alpha_2": "KZ", "alpha_3": "KAZ"},
    {"country_name": "Kenya", "alpha_2": "KE", "alpha_3": "KEN"},
    {"country_name": "Kiribati", "alpha_2": "KI", "alpha_3": "KIR"},
    {"country_name": "Kuwait", "alpha_2": "KW", "alpha_3": "KWT"},
    {"country_name": "Kyrgyzstan", "alpha_2": "KG", "alpha_3": "KGZ"},
    {"country_name": "Lao People's Democratic Republic", "alpha_2": "LA", "alpha_3": "LAO"},
    {"country_name": "Latvia", "alpha_2": "LV", "alpha_3": "LVA"},
    {"country_name": "Lebanon", "alpha_2": "LB", "alpha_3": "LBN"},
    {"country_name": "Lesotho", "alpha_2": "LS", "alpha_3": "LSO"},
    {"country_name": "Liberia", "alpha_2": "LR", "alpha_3": "LBR"},
    {"country_name": "Libya", "alpha_2": "LY", "alpha_3": "LBY"},
    {"country_name": "Liechtenstein", "alpha_2": "LI", "alpha_3": "LIE"},
    {"country_name": "Lithuania", "alpha_2": "LT", "alpha_3": "LTU"},
    {"country_name": "Luxembourg", "alpha_2": "LU", "alpha_3": "LUX"},
    {"country_name": "Macao", "alpha_2": "MO", "alpha_3": "MAC"},
    {"country_name": "Madagascar", "alpha_2": "MG", "alpha_3": "MDG"},
    {"country_name": "Malawi", "alpha_2": "MW", "alpha_3": "MWI"},
    {"country_name": "Malaysia", "alpha_2": "MY", "alpha_3": "MYS"},
    {"country_name": "Maldives", "alpha_2": "MV", "alpha_3": "MDV"},
    {"country_name": "Mali", "alpha_2": "ML", "alpha_3": "MLI"},
    {"country_name": "Malta", "alpha_2": "MT", "alpha_3": "MLT"},
    {"country_name": "Marshall Islands", "alpha_2": "MH", "alpha_3": "MHL"},
    {"country_name": "Martinique", "alpha_2": "MQ", "alpha_3": "MTQ"},
    {"country_name": "Mauritania", "alpha_2": "MR", "alpha_3": "MRT"},
    {"country_name": "Mauritius", "alpha_2": "MU", "alpha_3": "MUS"},
    {"country_name": "Mayotte", "alpha_2": "YT", "alpha_3": "MYT"},
    {"country_name": "Mexico", "alpha_2": "MX", "alpha_3": "MEX"},
    {"country_name": "Micronesia (Federated States of)", "alpha_2": "FM", "alpha_3": "FSM"},
    {"country_name": "Moldova (Republic of)", "alpha_2": "MD", "alpha_3": "MDA"},
    {"country_name": "Monaco", "alpha_2": "MC", "alpha_3": "MCO"},
    {"country_name": "Mongolia", "alpha_2": "MN", "alpha_3": "MNG"},
    {"country_name": "Montenegro", "alpha_2": "ME", "alpha_3": "MNE"},
    {"country_name": "Montserrat", "alpha_2": "MS", "alpha_3": "MSR"},
    {"country_name": "Morocco", "alpha_2": "MA", "alpha_3": "MAR"},
    {"country_name": "Mozambique", "alpha_2": "MZ", "alpha_3": "MOZ"},
    {"country_name": "Namibia", "alpha_2": "NA", "alpha_3": "NAM"},
    {"country_name": "Nauru", "alpha_2": "NR", "alpha_3": "NRU"},
    {"country_name": "Navassa Island", "alpha_2": "XV", "alpha_3": "XNV"},
    {"country_name": "Nepal", "alpha_2": "NP", "alpha_3": "NPL"},
    {"country_name": "Netherlands", "alpha_2": "NL", "alpha_3": "NLD"},
    {"country_name": "New Caledonia", "alpha_2": "NC", "alpha_3": "NCL"},
    {"country_name": "New Zealand", "alpha_2": "NZ", "alpha_3": "NZL"},
    {"country_name": "Nicaragua", "alpha_2": "NI", "alpha_3": "NIC"},
    {"country_name": "Nigeria", "alpha_2": "NG", "alpha_3": "NGA"},
    {"country_name": "Niger", "alpha_2": "NE", "alpha_3": "NER"},
    {"country_name": "Niue", "alpha_2": "NU", "alpha_3": "NIU"},
    {"country_name": "Norfolk Island", "alpha_2": "NF", "alpha_3": "NFK"},
    {"country_name": "Northern Mariana Islands", "alpha_2": "MP", "alpha_3": "MNP"},
    {"country_name": "Norway", "alpha_2": "NO", "alpha_3": "NOR"},
    {"country_name": "Oman", "alpha_2": "OM", "alpha_3": "OMN"},
    {"country_name": "Pakistan", "alpha_2": "PK", "alpha_3": "PAK"},
    {"country_name": "Palau", "alpha_2": "PW", "alpha_3": "PLW"},
    {"country_name": "Palmyra Atoll", "alpha_2": "XL", "alpha_3": "XPL"},
    {"country_name": "Panama", "alpha_2": "PA", "alpha_3": "PAN"},
    {"country_name": "Papua New Guinea", "alpha_2": "PG", "alpha_3": "PNG"},
    {"country_name": "Paracel Islands", "alpha_2": "XP", "alpha_3": "XPR"},
    {"country_name": "Paraguay", "alpha_2": "PY", "alpha_3": "PRY"},
    {"country_name": "Peru", "alpha_2": "PE", "alpha_3": "PER"},
    {"country_name": "Philippines", "alpha_2": "PH", "alpha_3": "PHL"},
    {"country_name": "Pitcairn Islands", "alpha_2": "PN", "alpha_3": "PCN"},
    {"country_name": "Poland", "alpha_2": "PL", "alpha_3": "POL"},
    {"country_name": "Portugal", "alpha_2": "PT", "alpha_3": "PRT"},
    {"country_name": "Puerto Rico", "alpha_2": "PR", "alpha_3": "PRI"},
    {"country_name": "Qatar", "alpha_2": "QA", "alpha_3": "QAT"},
    {"country_name": "Reunion", "alpha_2": "RE", "alpha_3": "REU"},
    {"country_name": "Romania", "alpha_2": "RO", "alpha_3": "ROU"},
    {"country_name": "Russian Federation", "alpha_2": "RU", "alpha_3": "RUS"},
    {"country_name": "Rwanda", "alpha_2": "RW", "alpha_3": "RWA"},
    {"country_name": "Saint Barthelemy", "alpha_2": "BL", "alpha_3": "BLM"},
    {"country_name": "Saint Helena, Ascension and Tristan da Cunha", "alpha_2": "SH", "alpha_3": "SHN"},
    {"country_name": "Saint Kitts and Nevis", "alpha_2": "KN", "alpha_3": "KNA"},
    {"country_name": "Saint Lucia", "alpha_2": "LC", "alpha_3": "LCA"},
    {"country_name": "Saint Martin (French part)", "alpha_2": "MF", "alpha_3": "MAF"},
    {"country_name": "Saint Pierre and Miquelon", "alpha_2": "PM", "alpha_3": "SPM"},
    {"country_name": "Saint Vincent and the Grenadines", "alpha_2": "VC", "alpha_3": "VCT"},
    {"country_name": "Samoa", "alpha_2": "WS", "alpha_3": "WSM"},
    {"country_name": "San Marino", "alpha_2": "SM", "alpha_3": "SMR"},
    {"country_name": "Sao Tome and Principe", "alpha_2": "ST", "alpha_3": "STP"},
    {"country_name": "Saudi Arabia", "alpha_2": "SA", "alpha_3": "SAU"},
    {"country_name": "Senegal", "alpha_2": "SN", "alpha_3": "SEN"},
    {"country_name": "Serbia", "alpha_2": "RS", "alpha_3": "SRB"},
    {"country_name": "Seychelles", "alpha_2": "SC", "alpha_3": "SYC"},
    {"country_name": "Sierra Leone", "alpha_2": "SL", "alpha_3": "SLE"},
    {"country_name": "Singapore", "alpha_2": "SG", "alpha_3": "SGP"},
    {"country_name": "Sint Maarten (Dutch part)", "alpha_2": "SX", "alpha_3": "SXM"},
    {"country_name": "Slovakia", "alpha_2": "SK", "alpha_3": "SVK"},
    {"country_name": "Slovenia", "alpha_2": "SI", "alpha_3": "SVN"},
    {"country_name": "Solomon Islands", "alpha_2": "SB", "alpha_3": "SLB"},
    {"country_name": "Somalia", "alpha_2": "SO", "alpha_3": "SOM"},
    {"country_name": "South Africa", "alpha_2": "ZA", "alpha_3": "ZAF"},
    {"country_name": "South Georgia and the South Sandwich Islands", "alpha_2": "GS", "alpha_3": "SGS"},
    {"country_name": "South Sudan", "alpha_2": "SS", "alpha_3": "SSD"},
    {"country_name": "Spain", "alpha_2": "ES", "alpha_3": "ESP"},
    {"country_name": "Spratly Islands", "alpha_2": "XS", "alpha_3": "XSP"},
    {"country_name": "Sri Lanka", "alpha_2": "LK", "alpha_3": "LKA"},
    {"country_name": "Sudan", "alpha_2": "SD", "alpha_3": "SDN"},
    {"country_name": "Suriname", "alpha_2": "SR", "alpha_3": "SUR"},
    {"country_name": "Svalbard and Jan Mayen", "alpha_2": "SJ", "alpha_3": "SJM"},
    {"country_name": "Sweden", "alpha_2": "SE", "alpha_3": "SWE"},
    {"country_name": "Switzerland", "alpha_2": "CH", "alpha_3": "CHE"},
    {"country_name": "Syrian Arab Republic", "alpha_2": "SY", "alpha_3": "SYR"},
    {"country_name": "Taiwan (Province of China)", "alpha_2": "TW", "alpha_3": "TWN"},
    {"country_name": "Tajikistan", "alpha_2": "TJ", "alpha_3": "TJK"},
    {"country_name": "Tanzania, United Republic of", "alpha_2": "TZ", "alpha_3": "TZA"},
    {"country_name": "Thailand", "alpha_2": "TH", "alpha_3": "THA"},
    {"country_name": "Timor-Leste", "alpha_2": "TL", "alpha_3": "TLS"},
    {"country_name": "Togo", "alpha_2": "TG", "alpha_3": "TGO"},
    {"country_name": "Tokelau", "alpha_2": "TK", "alpha_3": "TKL"},
    {"country_name": "Tonga", "alpha_2": "TO", "alpha_3": "TON"},
    {"country_name": "Trinidad and Tobago", "alpha_2": "TT", "alpha_3": "TTO"},
    {"country_name": "Tromelin Island", "alpha_2": "XT", "alpha_3": "XTR"},
    {"country_name": "Tunisia", "alpha_2": "TN", "alpha_3": "TUN"},
    {"country_name": "Türkiye", "alpha_2": "TR", "alpha_3": "TUR"},
    {"country_name": "Turkmenistan", "alpha_2": "TM", "alpha_3": "TKM"},
    {"country_name": "Turks and Caicos Islands", "alpha_2": "TC", "alpha_3": "TCA"},
    {"country_name": "Tuvalu", "alpha_2": "TV", "alpha_3": "TUV"},
    {"country_name": "Uganda", "alpha_2": "UG", "alpha_3": "UGA"},
    {"country_name": "Ukraine", "alpha_2": "UA", "alpha_3": "UKR"},
    {"country_name": "United Arab Emirates", "alpha_2": "AE", "alpha_3": "ARE"},
    {"country_name": "United Kingdom of Great Britain and Northern Ireland", "alpha_2": "GB", "alpha_3": "GBR"},
    {"country_name": "United States of America", "alpha_2": "US", "alpha_3": "USA"},
    {"country_name": "Uruguay", "alpha_2": "UY", "alpha_3": "URY"},
    {"country_name": "Uzbekistan", "alpha_2": "UZ", "alpha_3": "UZB"},
    {"country_name": "Vanuatu", "alpha_2": "VU", "alpha_3": "VUT"},
    {"country_name": "Venezuela (Bolivarian Republic of)", "alpha_2": "VE", "alpha_3": "VEN"},
    {"country_name": "Viet Nam", "alpha_2": "VN", "alpha_3": "VNM"},
    {"country_name": "Virgin Islands (British)", "alpha_2": "VG", "alpha_3": "VGB"},
    {"country_name": "Virgin Islands (U.S.)", "alpha_2": "VI", "alpha_3": "VIR"},
    {"country_name": "Wallis and Futuna", "alpha_2": "WF", "alpha_3": "WLF"},
    {"country_name": "Western Sahara", "alpha_2": "EH", "alpha_3": "ESH"},
    {"country_name": "Yemen", "alpha_2": "YE", "alpha_3": "YEM"},
    {"country_name": "Zambia", "alpha_2": "ZM", "alpha_3": "ZMB"},
    {"country_name": "Zimbabwe", "alpha_2": "ZW", "alpha_3": "ZWE"},
]


class SqlGetCountriesOperation(SqlBaseOperation):

    def _execute_operation(self):
        """Sql operation to get country codes from the ISO 3166 and GENC standard."""
        attribute = self.params.attribute_name or "country_name"
        if attribute not in ISO_3166_COUNTRY_CODES[0] or attribute not in GENC_COUNTRY_CODES[0]:
            raise ValueError(
                f"Invalid attribute name: {attribute}. Must be one of {list(ISO_3166_COUNTRY_CODES[0].keys())}"
            )

        iso_names = {entry["country_name"] for entry in ISO_3166_COUNTRY_CODES}
        master_list = ISO_3166_COUNTRY_CODES + [
            entry for entry in GENC_COUNTRY_CODES if entry["country_name"] not in iso_names
        ]

        attribute_list = list({entry[attribute] for entry in master_list})
        query = self._format_variable_list_to_query(vars=attribute_list)

        return SqlOperationResult(query=query, type="collection", subtype="Char")
