name: Check Lint and Format
on:
  # Can't be workflow_dispatch because it uses github.event.pull_request.base.sha
  workflow_call:

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      py: ${{ steps.changes.outputs.py }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Get changed files
        id: changes
        run: |
          echo "py=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} | grep .py$ | xargs)" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: get_changed_files
    # only run there are changed files
    if: ${{needs.get_changed_files.outputs.py}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install linters
        run: |
          pip install flake8==6.1.0
          pip install black==24.10.0
      - name: Run flake8
        run: |
          flake8 ${{needs.get_changed_files.outputs.py}} --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ${{needs.get_changed_files.outputs.py}} --ignore E203,W503 --count --statistics
      - name: Run black
        run: |
          black --check ${{needs.get_changed_files.outputs.py}}
