# This workflow will create venv, install requirements & run pytest.
# The purpose is to run unit tests automatically when we push a new to commit to a remote branch.

name: Analyse changes

on: [ pull_request ]


jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      py: ${{ steps.changes.outputs.py }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=py::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} | grep .py$ | xargs)"

  lint:
    runs-on: ubuntu-latest
    needs: changed_files
    # only run there are changed files
    if: ${{needs.changed_files.outputs.py}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install linters
        run: |
          pip install flake8
          pip install black

      - name: Run flake8
        run: |
          flake8 ${{needs.changed_files.outputs.py}} --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ${{needs.changed_files.outputs.py}} --count --statistics\

      - name: Run black
        run: |
         black --check ${{needs.changed_files.outputs.py}}