on:
  push:
    branches: [main]

permissions: {}

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/repository-dispatch@v3
        with:
          token: ${{ secrets.OPEN_RULES_PAT }}
          repository: cdisc-org/cdisc-open-rules
          event-type: engine-updated
