name: Unit Tests
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Running Tests
        run: |
          python -m pytest tests/unit/ --cov=cdisc_rules_engine --cov-fail-under=75
          python -m pytest tests/QARegressionTests/
